services:
  mcp-server:
    container_name: mcp-server
    build:
      context: .
      dockerfile: server.Dockerfile
    image: server:latest
    ports:
      - "8000:8000"
    env_file:
      - ./mcp_server/.env
    volumes:
      - ./logs/server:/app/mcp_server/logs
    restart: no

  ai-client:
    container_name: ai-client
    build:
      context: .
      dockerfile: client.Dockerfile
    image: client:latest
    ports:
      - "8501:8501"
    env_file:
      - ./ai_client/.env
    volumes:
      - ./ai_client/app:/app/ai_client/app  # Mount source code for hot-reload
      - ./logs/client:/app/ai_client/app/logs  # Must be after app mount to override
    command:
      uv run streamlit run app.py --server.port 8501 --server.enableCORS=false --server.enableXsrfProtection=false --server.runOnSave=true
    depends_on:
      - mcp-server
    restart: no
