name: Deploy the prod branch code to an Azure Virtual Machine

on:
  push:
    branches: [ prod ]

jobs:
  deployment:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Copy files using SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.MCP_PROD_HOST_VNET }}
          username: ${{ secrets.MCP_PROD_SSH_USERNAME }}
          key: ${{ secrets.MCP_PROD_PRIVATE_SSH_KEY }}
          source: "."
          target: "~/pankb-mcp"
  
      - name: Create the .env file and (re-)start containers over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.MCP_PROD_HOST_VNET }}
          username: ${{ secrets.MCP_PROD_SSH_USERNAME }}
          key: ${{ secrets.MCP_PROD_PRIVATE_SSH_KEY }}
          port: 22
          script: |
            cd ~/pankb-mcp

            # Create mcp_server/.env
            cat > mcp_server/.env << EOF
            MCP_API_KEY=${{secrets.MCP_API_KEY}}
            MONGODB_NAME=${{secrets.MONGODB_NAME}}
            MONGODB_PANKB_CONN_STRING=${{secrets.MONGODB_PANKB_CONN_STRING}}
            MONGODB_VECTOR_CONN_STRING=${{secrets.MONGODB_VECTOR_CONN_STRING}}
            EOF
            echo "=== mcp_server/.env ==="
            cat mcp_server/.env

            # Create ai_client/.env
            cat > ai_client/.env << EOF
            OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}}
            MCP_API_KEY=${{secrets.MCP_API_KEY}}
            MCP_SERVER_URL=${{secrets.MCP_SERVER_URL}}
            EOF
            echo "=== ai_client/.env ==="
            cat ai_client/.env

            docker compose down
            docker compose up -d --build --force-recreate --remove-orphans
            docker system prune --all --force